### ISSUE TITLE
What if internet is not working?

### ISSUE THREAD

**Issue by rohit1290** [CampusKarma/CampusKarma#11]
A page must be shown if the internet is not working.

**This is what I get if i try to open the app without internet (Was logged in previously)** 

![screenshot_2016-12-22-23-20-50](https://cloud.githubusercontent.com/assets/2772844/21435158/32a3a0bc-c89e-11e6-8262-8b436e92d68b.png)

**This is what I get if I logged in and then my internet is disconnected.**

![screenshot_2016-12-22-23-22-25](https://cloud.githubusercontent.com/assets/2772844/21435171/4a35ee4c-c89e-11e6-915c-14b4b57219c3.png)

**Few Ideas on how it should look like:**

![screenshot_2016-10-31-14-47-15](https://cloud.githubusercontent.com/assets/2772844/21435180/58ede5e8-c89e-11e6-9be6-28d0c292aa96.png)

![screenshot_2016-11-01-09-19-52](https://cloud.githubusercontent.com/assets/2772844/21435182/58f9b850-c89e-11e6-8760-8ac31ea6cdc8.png)

![screenshot_2016-12-11-23-36-21](https://cloud.githubusercontent.com/assets/2772844/21435181/58f1ce9c-c89e-11e6-898c-6b8f9cdd3616.png)

**Comment by Anandsoni14** [comment]
Files updated. https://github.com/CampusKarma/CampusKarma/blob/master/app/src/main/res/layout/refresh_page.xml
