### ISSUE TITLE
About, FAQs - Page not working

### ISSUE THREAD

**Issue by rohit1290** [CampusKarma/CampusKarma#3]
About, FAQs page not working.

The app should have following pages:

- About Us
- FAQs
- Terms
- Privacy

**Comment by Anandsoni14** [comment]
I have files. But haven't added it because of design issue. Once I resolves it design issue. I will add it. Its not bug. 
That's why I am closing it.

**Comment by rohit1290** [comment]
![screenshot_2016-10-31-15-22-29](https://cloud.githubusercontent.com/assets/2772844/21435824/cefc95c4-c8a1-11e6-8369-47c450b0c096.png)
