### ISSUE TITLE
Facebook Login not working

### ISSUE THREAD

**Issue by rohit1290** [CampusKarma/CampusKarma#4]
Issue start date: 22 Dec 2016
After Anand's https://github.com/CampusKarma/CampusKarma/commit/d10a6d703ef3527b7d187de0ffb2bbfc4fff80be push, facebook login is not working)

**Comment by Anandsoni14** [comment]
This might be problem due to FacebookSDK Initialization. @rwikdutta please check that in Firebase Console.
