### ISSUE TITLE
Side Bar - Adding of Menus

### ISSUE THREAD

**Issue by rohit1290** [CampusKarma/CampusKarma#7]
SideBar should have the following module

- Home (Activity)
- Events
- Groups
- Files
- Blog
- Wire Post
- Photos
- Videos
- -----------
- Messages
- Profile
- Friends

**Comment by Anandsoni14** [comment]
Please group them in 4-4 topics. as per google guidelines.

**Comment by rohit1290** [comment]
I didn't found that 4-4 grouping concept anywhere.
https://material.io/guidelines/components/menus.html

**Comment by Anandsoni14** [comment]
@rohit1290 Can you tell me, which section gets most click in Ascending order.

**Comment by rohit1290** [comment]
Were you asking for this? The chart is as per last 1 year of user data.

![capture](https://cloud.githubusercontent.com/assets/2772844/21538197/5ae02cea-cdc0-11e6-9004-6826893b9b1c.PNG)

**Comment by Anandsoni14** [comment]
Yeah ! Exactly like this. If you have hotmaps or In google Analytics. But
in full picture. then mail me.

Anand Soni
UX/UI Designer and Android Developer

**Comment by rohit1290** [comment]
Have added ur email ID a*********.****a@gmail.com to the GA account
