### ISSUE TITLE
Single Page File View - Moving "File Name" location

### ISSUE THREAD

**Issue by rohit1290** [CampusKarma/CampusKarma#9]
It will be best, if we keep the file name above and other details like user and date etc below that.

![screenshot_2016-12-22-20-39-03](https://cloud.githubusercontent.com/assets/2772844/21434627/8bbf67ec-c89b-11e6-8206-e12c7d16d88a.png)

**Comment by Anandsoni14** [comment]
Title cannot be made like marquee. But reduced the and position of Title in layout.
